2024-03-14 12:44:13,620 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5555
2024-03-14 12:44:13,620 - INFO - [33mPress CTRL+C to quit[0m
2024-03-14 12:44:37,354 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5555
2024-03-14 12:44:37,354 - INFO - [33mPress CTRL+C to quit[0m
2024-03-14 12:44:51,341 - INFO - 127.0.0.1 - - [14/Mar/2024 12:44:51] "POST /login HTTP/1.1" 200 -
2024-03-14 12:47:32,467 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5555
2024-03-14 12:47:32,467 - INFO - [33mPress CTRL+C to quit[0m
2024-03-14 12:47:59,323 - INFO - 127.0.0.1 - - [14/Mar/2024 12:47:59] "GET /events HTTP/1.1" 200 -
2024-03-14 12:48:25,849 - INFO - User details accessed
2024-03-14 12:48:25,859 - INFO - 127.0.0.1 - - [14/Mar/2024 12:48:25] "GET /users/1 HTTP/1.1" 200 -
2024-03-14 12:48:37,911 - INFO - User details accessed
2024-03-14 12:48:37,914 - INFO - 127.0.0.1 - - [14/Mar/2024 12:48:37] "GET /users/2 HTTP/1.1" 200 -
2024-03-14 12:54:47,477 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5555
2024-03-14 12:54:47,477 - INFO - [33mPress CTRL+C to quit[0m
2024-03-14 12:54:54,842 - INFO - User, johndoe@gmail.com, details accessed
2024-03-14 12:54:54,852 - INFO - 127.0.0.1 - - [14/Mar/2024 12:54:54] "GET /users/2 HTTP/1.1" 200 -
2024-03-14 14:19:22,900 - INFO - 127.0.0.1 - - [14/Mar/2024 14:19:22] "POST /login HTTP/1.1" 200 -
2024-03-14 14:19:59,859 - INFO - 127.0.0.1 - - [14/Mar/2024 14:19:59] "GET /events HTTP/1.1" 200 -
2024-03-14 14:25:10,278 - ERROR - Exception on /events [POST]
Traceback (most recent call last):
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/home/harris/Development/code/phase5/DevProject/Event-Planner 5/Event-Planner/server/app.py", line 262, in post
    end_date = datetime.strptime(end_date_str, '%m/%d/%Y').date()
  File "/usr/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '16/3/2024' does not match format '%m/%d/%Y'
2024-03-14 14:25:10,374 - INFO - 127.0.0.1 - - [14/Mar/2024 14:25:10] "[35m[1mPOST /events HTTP/1.1[0m" 500 -
2024-03-14 14:26:16,153 - ERROR - Exception on /events [POST]
Traceback (most recent call last):
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/home/harris/Development/code/phase5/DevProject/Event-Planner 5/Event-Planner/server/app.py", line 258, in post
    start_date = datetime.strptime(start_date_str, '%m/%d/%Y').date()
  File "/usr/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '09-3-2024' does not match format '%m/%d/%Y'
2024-03-14 14:26:16,153 - INFO - 127.0.0.1 - - [14/Mar/2024 14:26:16] "[35m[1mPOST /events HTTP/1.1[0m" 500 -
2024-03-14 14:26:53,051 - ERROR - Exception on /events [POST]
Traceback (most recent call last):
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/home/harris/Development/code/phase5/DevProject/Event-Planner 5/Event-Planner/server/app.py", line 258, in post
    start_date = datetime.strptime(start_date_str, '%m/%d/%Y').date()
  File "/usr/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '03-09-2024' does not match format '%m/%d/%Y'
2024-03-14 14:26:53,052 - INFO - 127.0.0.1 - - [14/Mar/2024 14:26:53] "[35m[1mPOST /events HTTP/1.1[0m" 500 -
2024-03-14 14:27:15,020 - ERROR - Exception on /events [POST]
Traceback (most recent call last):
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/home/harris/Development/code/phase5/DevProject/Event-Planner 5/Event-Planner/server/app.py", line 258, in post
    start_date = datetime.strptime(start_date_str, '%m/%d/%Y').date()
  File "/usr/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '03-09-2024' does not match format '%m/%d/%Y'
2024-03-14 14:27:15,020 - INFO - 127.0.0.1 - - [14/Mar/2024 14:27:15] "[35m[1mPOST /events HTTP/1.1[0m" 500 -
2024-03-14 14:28:55,812 - INFO - 127.0.0.1 - - [14/Mar/2024 14:28:55] "[35m[1mPOST /events HTTP/1.1[0m" 201 -
2024-03-14 14:39:18,125 - ERROR - Exception on /users/2 [GET]
Traceback (most recent call last):
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 340, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/utils.py", line 128, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/jwt_manager.py", line 556, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/tokens.py", line 95, in _decode_jwt
    decoded_token = jwt.decode(
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/jwt/api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/jwt/api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/jwt/api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/jwt/api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
2024-03-14 14:39:18,167 - INFO - 127.0.0.1 - - [14/Mar/2024 14:39:18] "[35m[1mGET /users/2 HTTP/1.1[0m" 500 -
2024-03-14 14:39:34,928 - INFO - 127.0.0.1 - - [14/Mar/2024 14:39:34] "POST /login HTTP/1.1" 200 -
2024-03-14 14:39:35,425 - INFO - 127.0.0.1 - - [14/Mar/2024 14:39:35] "POST /login HTTP/1.1" 200 -
2024-03-14 14:39:47,798 - INFO - User, johndoe@gmail.com, details accessed
2024-03-14 14:39:47,802 - INFO - 127.0.0.1 - - [14/Mar/2024 14:39:47] "GET /users/2 HTTP/1.1" 200 -
2024-03-14 14:41:59,150 - INFO - 127.0.0.1 - - [14/Mar/2024 14:41:59] "GET /events HTTP/1.1" 200 -
2024-03-14 14:49:57,860 - INFO - 127.0.0.1 - - [14/Mar/2024 14:49:57] "[31m[1mPOST /login HTTP/1.1[0m" 400 -
2024-03-14 14:50:06,122 - INFO - 127.0.0.1 - - [14/Mar/2024 14:50:06] "POST /login HTTP/1.1" 200 -
2024-03-14 14:50:45,203 - INFO - 127.0.0.1 - - [14/Mar/2024 14:50:45] "GET /users HTTP/1.1" 200 -
2024-03-14 14:51:05,659 - INFO - User, wazza10@manu.com, details accessed
2024-03-14 14:51:05,663 - INFO - 127.0.0.1 - - [14/Mar/2024 14:51:05] "GET /users/1 HTTP/1.1" 200 -
2024-03-14 19:17:05,138 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5555
2024-03-14 19:17:05,149 - INFO - [33mPress CTRL+C to quit[0m
2024-03-14 19:17:26,706 - INFO - 127.0.0.1 - - [14/Mar/2024 19:17:26] "POST /login HTTP/1.1" 200 -
2024-03-14 19:18:02,438 - INFO - 127.0.0.1 - - [14/Mar/2024 19:18:02] "GET /events HTTP/1.1" 200 -
2024-03-14 19:27:52,036 - INFO - User, johndoe@gmail.com, details accessed
2024-03-14 19:27:52,040 - INFO - 127.0.0.1 - - [14/Mar/2024 19:27:52] "GET /users/1 HTTP/1.1" 200 -
2024-03-14 20:58:35,940 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5555
2024-03-14 20:58:35,952 - INFO - [33mPress CTRL+C to quit[0m
2024-03-14 20:58:43,096 - INFO - 127.0.0.1 - - [14/Mar/2024 20:58:43] "POST /login HTTP/1.1" 200 -
2024-03-14 20:59:04,415 - INFO - 127.0.0.1 - - [14/Mar/2024 20:59:04] "GET /events HTTP/1.1" 200 -
2024-03-14 20:59:12,361 - INFO - User, johndoe@gmail.com, details accessed
2024-03-14 20:59:12,366 - INFO - 127.0.0.1 - - [14/Mar/2024 20:59:12] "GET /users/1 HTTP/1.1" 200 -
2024-03-14 21:05:31,008 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5555
2024-03-14 21:05:31,038 - INFO - [33mPress CTRL+C to quit[0m
2024-03-14 21:05:37,229 - INFO - 127.0.0.1 - - [14/Mar/2024 21:05:37] "GET /events HTTP/1.1" 200 -
2024-03-14 21:06:52,071 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5555
2024-03-14 21:06:52,071 - INFO - [33mPress CTRL+C to quit[0m
2024-03-14 21:06:55,980 - INFO - 127.0.0.1 - - [14/Mar/2024 21:06:55] "GET /events HTTP/1.1" 200 -
2024-03-14 21:49:11,676 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5555
2024-03-14 21:49:11,717 - INFO - [33mPress CTRL+C to quit[0m
2024-03-14 21:49:20,641 - ERROR - Exception on /tasks [GET]
Traceback (most recent call last):
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 340, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/utils.py", line 128, in decode_token
    return jwt_manager._decode_jwt_from_config(encoded_token, csrf_value, allow_expired)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/jwt_manager.py", line 556, in _decode_jwt_from_config
    return _decode_jwt(**kwargs, allow_expired=allow_expired)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/tokens.py", line 95, in _decode_jwt
    decoded_token = jwt.decode(
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/jwt/api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/jwt/api_jwt.py", line 162, in decode_complete
    self._validate_claims(
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/jwt/api_jwt.py", line 248, in _validate_claims
    self._validate_exp(payload, now, leeway)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/jwt/api_jwt.py", line 306, in _validate_exp
    raise ExpiredSignatureError("Signature has expired")
jwt.exceptions.ExpiredSignatureError: Signature has expired
2024-03-14 21:49:20,698 - INFO - 127.0.0.1 - - [14/Mar/2024 21:49:20] "[35m[1mGET /tasks HTTP/1.1[0m" 500 -
2024-03-14 21:49:36,974 - INFO - 127.0.0.1 - - [14/Mar/2024 21:49:36] "POST /login HTTP/1.1" 200 -
2024-03-14 21:50:04,477 - ERROR - Exception on /tasks [GET]
Traceback (most recent call last):
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/home/harris/Development/code/phase5/DevProject/Event-Planner 5/Event-Planner/server/app.py", line 425, in get
    return make_response(jsonify(tasks_list))
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/json/provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.10/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home/harris/.local/share/virtualenvs/server-w-e4xBA_/lib/python3.10/site-packages/flask/json/provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type time is not JSON serializable
2024-03-14 21:50:04,570 - INFO - 127.0.0.1 - - [14/Mar/2024 21:50:04] "[35m[1mGET /tasks HTTP/1.1[0m" 500 -
2024-03-14 21:51:43,428 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5555
2024-03-14 21:51:43,428 - INFO - [33mPress CTRL+C to quit[0m
2024-03-14 21:51:46,734 - INFO - 127.0.0.1 - - [14/Mar/2024 21:51:46] "GET /tasks HTTP/1.1" 200 -
